// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package generated_sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID       int32
	UserName     string
	Email        string
	UserPassword string
	Age          int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	UserType     pgtype.Text
}
